/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas.modul10;

/**
 *
 * @author PC RPL - R1
 */
public class latihan_10 extends javax.swing.JFrame {

    /**
     * Creates new form latihan_10
     */
    public latihan_10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eData3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eData4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eSisi1 = new javax.swing.JTextField();
        eSisi2 = new javax.swing.JTextField();
        eSisi3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        eRadius = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        meltBersih = new javax.swing.JMenuItem();
        menHitung = new javax.swing.JMenu();
        meltKali = new javax.swing.JMenuItem();
        meltBagi = new javax.swing.JMenuItem();
        meltTambah = new javax.swing.JMenuItem();
        meltKurang = new javax.swing.JMenuItem();
        menPersegi = new javax.swing.JMenu();
        meltLuasP = new javax.swing.JMenuItem();
        meltKelilingP = new javax.swing.JMenuItem();
        menSegitiga = new javax.swing.JMenu();
        meltLuasS = new javax.swing.JMenuItem();
        meltKelilingS = new javax.swing.JMenuItem();
        menLingkaran = new javax.swing.JMenu();
        meltLuasL = new javax.swing.JMenuItem();
        meltKelilingL = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Panjang");

        jLabel2.setText("Lebar");

        jLabel3.setText("Hasil");

        jLabel4.setText("Alas");

        jLabel5.setText("Tinggi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("PERSEGI PANJANG");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("LINGKARAN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("SEGITIGA");

        jLabel9.setText("Sisi 1");

        jLabel10.setText("Sisi 2");

        jLabel11.setText("Sisi 3");

        jLabel12.setText("Radius");

        menFile.setText("File");
        jMenuBar1.add(menFile);

        menProses.setText("Proses");

        meltBersih.setText("Bersih");
        meltBersih.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltBersihStateChanged(evt);
            }
        });
        meltBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltBersihActionPerformed(evt);
            }
        });
        menProses.add(meltBersih);

        menHitung.setText("Hitung");

        meltKali.setText("Kali");
        meltKali.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltKaliStateChanged(evt);
            }
        });
        menHitung.add(meltKali);

        meltBagi.setText("Bagi");
        meltBagi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltBagiStateChanged(evt);
            }
        });
        menHitung.add(meltBagi);

        meltTambah.setText("Tambah");
        meltTambah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltTambahStateChanged(evt);
            }
        });
        menHitung.add(meltTambah);

        meltKurang.setText("Kurang");
        meltKurang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltKurangStateChanged(evt);
            }
        });
        menHitung.add(meltKurang);

        menProses.add(menHitung);

        menPersegi.setText("Persegi Panjang");

        meltLuasP.setText("Luas");
        meltLuasP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltLuasPStateChanged(evt);
            }
        });
        menPersegi.add(meltLuasP);

        meltKelilingP.setText("Keliling");
        meltKelilingP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltKelilingPStateChanged(evt);
            }
        });
        menPersegi.add(meltKelilingP);

        menProses.add(menPersegi);

        menSegitiga.setText("Segitiga");

        meltLuasS.setText("Luas");
        meltLuasS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltLuasSStateChanged(evt);
            }
        });
        menSegitiga.add(meltLuasS);

        meltKelilingS.setText("Keliling");
        meltKelilingS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltKelilingSStateChanged(evt);
            }
        });
        menSegitiga.add(meltKelilingS);

        menProses.add(menSegitiga);

        menLingkaran.setText("Lingkaran");

        meltLuasL.setText("Luas");
        meltLuasL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltLuasLStateChanged(evt);
            }
        });
        menLingkaran.add(meltLuasL);

        meltKelilingL.setText("Keliling");
        meltKelilingL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meltKelilingLStateChanged(evt);
            }
        });
        menLingkaran.add(meltKelilingL);

        menProses.add(menLingkaran);

        jMenuBar1.add(menProses);

        menBantuan.setText("Bantuan");
        jMenuBar1.add(menBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(eHasil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eData1))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(eData2)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eSisi1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eData4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eSisi2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eSisi3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(eData3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 576, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(eData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(eRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(eData4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(eSisi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSisi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSisi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltKaliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltKaliStateChanged
       int Data1 = Integer.parseInt(eData1.getText());
       int Data2 = Integer.parseInt(eData2.getText()); 
       int Hasil; 
        Hasil = Data1 * Data2; 
        eHasil.setText(String.valueOf(Hasil));

    }//GEN-LAST:event_meltKaliStateChanged

    private void meltBagiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltBagiStateChanged
        int Data1 = Integer.parseInt(eData1.getText());
        int Data2 = Integer.parseInt(eData2.getText()); 
        int Hasil; 
        Hasil = Data1 / Data2; 
        eHasil.setText(String.valueOf(Hasil));
    }//GEN-LAST:event_meltBagiStateChanged

    private void meltTambahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltTambahStateChanged
       int Data1 = Integer.parseInt(eData1.getText());
        int Data2 = Integer.parseInt(eData2.getText()); 
        int Hasil; 
        Hasil = Data1 + Data2; 
        eHasil.setText(String.valueOf(Hasil));
    }//GEN-LAST:event_meltTambahStateChanged

    private void meltKurangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltKurangStateChanged
       int Data1 = Integer.parseInt(eData1.getText());
        int Data2 = Integer.parseInt(eData2.getText()); 
        int Hasil; 
        Hasil = Data1 - Data2; 
        eHasil.setText(String.valueOf(Hasil));
    }//GEN-LAST:event_meltKurangStateChanged

    private void meltBersihStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltBersihStateChanged
      
    }//GEN-LAST:event_meltBersihStateChanged

    private void meltBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltBersihActionPerformed
           // Clear all input and output fields
    eData1.setText("");
    eData2.setText("");
    eData3.setText("");
    eData4.setText("");
    eHasil.setText("");
    eSisi1.setText("");
    eSisi2.setText("");
    eSisi3.setText("");
    eRadius.setText("");
    }//GEN-LAST:event_meltBersihActionPerformed

    private void meltLuasPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltLuasPStateChanged
        int panjang = Integer.parseInt(eData1.getText());
        int lebar = Integer.parseInt(eData2.getText()); 
        int luas; 
        luas = panjang * lebar; 
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuasPStateChanged

    private void meltKelilingPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltKelilingPStateChanged
       int panjang = Integer.parseInt(eData1.getText());
        int lebar = Integer.parseInt(eData2.getText()); 
        int keliling; 
        keliling = 2 * (panjang + lebar); 
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingPStateChanged

    private void meltLuasSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltLuasSStateChanged
        int alas = Integer.parseInt(eData3.getText());
        int tinggi = Integer.parseInt(eData4.getText());

        // Hitung luas segitiga
        int luas = (alas * tinggi) / 2;

        // Tampilkan hasil di text field eHasil
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuasSStateChanged

    private void meltKelilingSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltKelilingSStateChanged
        // Ambil input dari pengguna
        int sisi1 = Integer.parseInt(eSisi1.getText());
        int sisi2 = Integer.parseInt(eSisi2.getText());
        int sisi3 = Integer.parseInt(eSisi3.getText());

        // Hitung keliling segitiga
        int keliling = sisi1 + sisi2 + sisi3;

        // Tampilkan hasil di text field eHasil
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingSStateChanged

    private void meltLuasLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltLuasLStateChanged
        // Ambil input dari pengguna
        int radius = Integer.parseInt(eRadius.getText());

        // Hitung luas lingkaran
        double luas = Math.PI * radius * radius;

        // Tampilkan hasil di text field eHasil
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuasLStateChanged

    private void meltKelilingLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meltKelilingLStateChanged
       // Ambil input dari pengguna
    int radius = Integer.parseInt(eRadius.getText());

    // Hitung keliling lingkaran
    double keliling = 2 * Math.PI * radius;

    // Tampilkan hasil di text field eHasil
    eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingLStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan_10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eData3;
    private javax.swing.JTextField eData4;
    private javax.swing.JTextField eHasil;
    private javax.swing.JTextField eRadius;
    private javax.swing.JTextField eSisi1;
    private javax.swing.JTextField eSisi2;
    private javax.swing.JTextField eSisi3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meltBagi;
    private javax.swing.JMenuItem meltBersih;
    private javax.swing.JMenuItem meltKali;
    private javax.swing.JMenuItem meltKelilingL;
    private javax.swing.JMenuItem meltKelilingP;
    private javax.swing.JMenuItem meltKelilingS;
    private javax.swing.JMenuItem meltKurang;
    private javax.swing.JMenuItem meltLuasL;
    private javax.swing.JMenuItem meltLuasP;
    private javax.swing.JMenuItem meltLuasS;
    private javax.swing.JMenuItem meltTambah;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menHitung;
    private javax.swing.JMenu menLingkaran;
    private javax.swing.JMenu menPersegi;
    private javax.swing.JMenu menProses;
    private javax.swing.JMenu menSegitiga;
    // End of variables declaration//GEN-END:variables
}
